version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: zarns/client-image:latest
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: zarns/server-image:latest
    ports:
      - "3001:3001"
