export default function Head() {
    return (
        <>
            <title>Telestrations</title>
            <meta
                content="width=device-width, initial-scale=1"
                name="viewport"
            />
            <meta name="description" content="Generated by create next app" />
            <link href="/favicon.ico?" rel="icon" sizes="any" />
        </>
    )
}
